config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
root 'suggestions#home'

get '/Suggestions', to: redirect("suggestions/index")

resources :suggestions

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/suggestions_controller.rb
class SuggestionsController < ApplicationController
  def index
    # require 'httparty'

    user = params[:items][:age] + " + " + params[:items][:activities] + " + " + params[:items][:style]
    url = "http://api.walmartlabs.com/v1/search?query=#{user}&format=json&apiKey=4ev5epchtbuy49e3w7b3up5d"
    response = HTTParty.get(url).to_h
    @items = response["items"]
  end

  def show
    id = params[:id]
    url = "http://api.walmartlabs.com/v1/items?ids=#{id}&format=json&apiKey=4ev5epchtbuy49e3w7b3up5d"
    response = HTTParty.get(url).to_h
    @items = response["items"]
  end

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/suggestions_helper.rb
module SuggestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <%= favicon_link_tag asset_path('gyft.jpg'), :rel => 'icon', :type =>  'image/jpg' %>

    <title>GFYT.</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/suggestions/home.html.erb
<div class = "topbar">
  <button class="topbutton" type="button">HOME</button>
  <button class="topbutton" type="button">SHOP</button>
  <button class="topbutton" type="button">ABOUT GYFT</button>
</div>
<div class="photohere">
  <img class= "mainpicture" src="assets/giphy.gif">
  <div class="title">
    <hr>
    <h1>GYFT.</h1>
    <hr>
    <h5 class="caption">Shopping for strangers.</h5>
  </div>
</div>

<% categories = ['movies star wars', 'movies marvel avengers', 'music vinyl', 'music karaoke', 'books food wine', 'books crafts hobbies', 'home glam accessories', 'home boho accessories',
  'nintendo 3ds game', 'xbox one games', 'nintendo switch games',
  'playstation vr', 'pets fish', 'pets reptiles','recreation golf',
  'specialty gift card', 'mugs', 'throw pillows', 'posters'] %>


<h2 class="quizheader">Lets help you put together</h2> <h1 class="quizheader">the perfect Gyft!</h1>

<div class="quizwrapper">
  <%= form_for :items, :url => suggestions_path, :html => {id: "home_form"}, method: :get  do |form| %>

<div class="questionbox first active">
  <h1 class="question">Age?</h1>

  <div class="multiplechoice">
    <ul>
      <% [["baby toys",'Toddler'], ["toys", 'Child'],["electronics",'Young Adult'], ["storage", 'Adult'], ["pioneer woman", 'Senior'],[categories.shuffle.first, "I don't know! Surprise me!"]].each do |item| %>
      <li>
        <%= form.radio_button :age, item[0], id: item[0].parameterize, class: 'age' %>
        <%= form.label :age, item[1], class: 'f-option', for: item[0].parameterize %>
        <div class="check"><div class="inside"></div></div>
      </li>
      <% end %>
    </ul>
  </div>
  </div>

  <div class="questionbox">

    <h1 class = "question">Describe their ideal afternoon...</h1>
    <div class="multiplechoice">
      <ul>
        <% [["artificial plants",'A brisk stroll through the park.'], ["Books", 'Enjoying a cup of tea over a good book'], ["tablet", 'Fidgeting with the latest gadget'], ["fitness", 'Reps at the gym.'], ["", "I don't know!"]].each do |item| %>
        <li>
          <%= form.radio_button :activities, item[0], id: item[0].parameterize%>
          <%= form.label :activities, item[1], for: nil, for: item[0].parameterize%>
          <div class="check"><div class="inside"></div></div>
        </li>
        <%end %>
      </ul>
    </div>
  </div>


  <div class="questionbox last">

    <h1 class = "question">Their style is best described as...</h1>
    <div class="multiplechoice">
      <ul>
        <% [["midcentury",'Minimalist and Modern'], ["wall art", 'Classic and Sophisticated'],["pinatas",  'Delightfully Quirky'], ["planters", 'Au Naturale'],["", "I don't know!"]].each do |item| %>
        <li>
          <%= form.radio_button :style, item[0], id: (item[0].blank? ? item[1] : item[0]).parameterize%>
          <%= form.label :style, item[1], for: (item[0].blank? ? 'blank' : item[0].parameterize )%>
          <div class="check"><div class="inside"></div></div>
        </li>

        <% end %>
      </ul>
    </div>
  </div>

<button class="left-arrow"><</button>
<button class="right-arrow">></button>

</div>


  <div class = "submit">
    <%= form.submit "Generate My GYFT", :id => 'submit_form', data: { disable_with: false} %>
  </div>

  <% end %>
</div>

app/views/suggestions/index.html.erb
<head>
<link rel="icon" type="image/jpg" href="/assets/gfyt.jpg"/>
</head>

<div class = "topbars">
<button class="topbuttons" type="button">HOME</button>
<button class="topbuttons" type="button">SHOP</button>
<button class="topbuttons" type="button">ABOUT GYFT</button>
</div>
<br>
<br>
<br>






<h2 class = "gift-suggestions">GYFT SUGGESTIONS.</h2>
<img class= "ribbonpicture" src="assets/bowhorizontal.png">
<br><br><br>


<div class = "results_wrapper">

  <% @items.each do |x|%>
  <div class = "items">
    <span class="item_name"><%= x["name"] %> </span>
    <!-- <span class='test'>test</span> -->
    <p class= "item_image"> <%= link_to image_tag(x['largeImage']), suggestion_path(x['itemId'])%></p>
    </div>
    <%end %>
  </div>

app/views/suggestions/show.html.erb
<div class="wholebody">

<div class = "topbars">
<button class="topbuttons" type="button">HOME</button>
<button class="topbuttons" type="button">SHOP</button>
<button class="topbuttons" type="button">ABOUT GYFT</button>
</div>
<br>
<br>
<br>




<hr class="style1">
<h2 class = "gyft-suggestions">Is this</h2> <h1 class = "gyft-suggestions">THE ONE?</h1>
<hr class="style1">

<div class="outside_api">
  <% @items.each do |x|%>
  <div class= "items">
  <center><p class= "show_name"><%= x["name"] %> <br></p></center>

    <p><%=image_tag(x['largeImage']) %></p> <br>
    <span class="item_price"> <%=  x["salePrice"] %><br><span class= "item_buy"><%= link_to "Purchase", x["productUrl"], :target => "_blank" %></span><br>
  <center>  <p class= "show_description"> <%= x["shortDescription"] %></p><br></center>
    <!-- <span class="item_price"> <%=  x["salePrice"] %><span class= "item_buy"><%= link_to "Purchase", x["productUrl"], :target => "_blank" %></span><br> -->
  </div>
  <%end %>
</div>
</div>